//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by C3Edit.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDS_SCRIPTING_MENU              126
#define IDS_OBJECTS_WND                 127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDS_RESOURCESPY_MENU            129
#define IDR_C3EditTYPE                  130
#define ID_RESOURCESPY_RELOAD           130
#define ID_WINDOW_MANAGER               131
#define IDS_TOOLBAR_RESOURCESPY         131
#define IDS_RESOURCESPY_WND             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_PROTOVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPS_TOGGLEHIDDEN           152
#define ID_PROPERTIES2                  153
#define ID_PROPS_ADD                    153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDS_CLOSE                       195
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_TOOLBAR_3DTOOLS             259
#define IDS_TOOLBAR_AXES                260
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDC_CAMERA_PANTILT              307
#define IDC_TRANSLATE                   308
#define IDC_ROTATE                      309
#define IDC_SCALE                       310
#define IDD_EDITPROTOTYPE               310
#define IDC_SELECT                      311
#define IDC_SELECT_MINUS                312
#define IDC_SELECT_PLUS                 313
#define IDC_UNISCALE                    314
#define IDC_WAND                        315
#define IDC_CURSOR9                     316
#define IDC_ZOOM                        317
#define IDR_TOOLBAR_3DTOOLS             318
#define IDR_TOOLBAR_AXES                319
#define IDR_TOOLBAR_SCRIPTING           320
#define ID_AXIS_X                       321
#define ID_AXIS_Y                       322
#define ID_AXIS_Z                       323
#define ID_AXIS_SCREENREL               324
#define ID_TOOL_SELECT                  325
#define ID_TOOL_TRANSLATE               326
#define IDR_ACC_CODE_EDIT               326
#define ID_TOOL_ROTATE                  327
#define ID_TOOL_UNISCALE                328
#define ID_TOOL_SCALE                   329
#define ID_TOOL_WAND                    330
#define IDD_EXTENSIONMAPPER             331
#define IDD_GRAPHEDITOR                 332
#define IDD_GRAPHNODE                   333
#define ID_VIEW_SCRIPTINGWND            334
#define IDS_SCRIPTING_WND               335
#define IDI_RESOURCESPY_WND             335
#define IDI_SCRIPTING_WND               336
#define IDI_SCRIPTING_WND_HC            337
#define ID_SCRIPT_UPDATE                339
#define ID_SCRIPT_ASSIGN                340
#define IDI_RESOURCESPY_WND_HC          340
#define ID_SCRIPT_RUN                   341
#define IDS_SCRIPT_UPDATE               342
#define IDR_POPUP_RESOURCESPY           342
#define IDS_SCRIPT_ASSIGN               343
#define IDS_SCRIPT_RUN                  344
#define IDD_CREATEPROPERTY              344
#define IDS_POPUP_GRAPH                 345
#define IDS_SCRIPTEDITOR_STATUS_NAME    346
#define IDS_SCRIPTEDITOR_STATUS_ROWCOL  347
#define IDS_TOOLBAR_SCRIPTING           348
#define IDR_ACCELERATOR1                348
#define ID_SEARCH                       349
#define IDS_PROTOTYPE_VIEW              350
#define IDR_PROTOTREE                   351
#define IDD_BRUSHSETTINGS               351
#define IDB_CHECKBOX                    352
#define IDR_POPUP_GRAPH                 353
#define IDR_TOOLBAR_RESOURCESPY         353
#define IDI_OBJECTS_WND                 354
#define IDI_OBJECTS_WND_HC              355
#define IDR_POPUP_SCRIPTING             356
#define ID_VIEW_OBJECTSWND              357
#define ID_SCRIPTEDITOR_STATUS_NAME     358
#define ID_SCRIPTEDITOR_STATUS_ROWCOL   359
#define ID_VIEW_RESOURCESPYWND          362
#define IDD_PACKFILEMANAGER             364
#define IDC_PROPERTIES                  1000
#define IDC_COMPONENTS                  1001
#define IDC_NAME                        1002
#define IDC_FLAGS                       1003
#define IDC_NODEPROPERTIES              1005
#define IDC_BUTTON_INPUT1               1006
#define IDC_BUTTON_OUTPUT1              1007
#define IDC_EXTLIST                     1010
#define IDC_RESTYPECB                   1011
#define IDC_PATHLIST                    1012
#define IDC_EDIT_PROPNAME               1012
#define IDC_EDIT_PROPFCC                1013
#define IDC_COMBO_PROPTYPE              1014
#define IDC_COMBO_PROPASPECT            1015
#define IDC_PACKFILELIST                1015
#define IDC_CHECK_YAW                   1016
#define IDC_EDIT_MINYAW                 1017
#define IDC_EDIT_MAXYAW                 1018
#define IDC_CHECK_PITCH                 1019
#define IDC_EDIT_MINPITCH               1020
#define IDC_EDIT_MAXPITCH               1021
#define IDC_CHECK_ROLL                  1022
#define IDC_EDIT_MINROLL                1023
#define IDC_EDIT_MAXROLL                1024
#define IDC_CHECK_SCLX                  1025
#define IDC_EDIT_MINSCLX                1026
#define IDC_EDIT_MAXSCLX                1027
#define IDC_CHECK_SCLY                  1028
#define IDC_EDIT_MINSCLY                1029
#define IDC_EDIT_MAXSCLY                1030
#define IDC_CHECK_SCLZ                  1031
#define IDC_EDIT_MINSCLZ                1032
#define IDC_EDIT_MAXSCLZ                1033
#define IDC_CHECK_LOCKXY                1034
#define IDC_CHECK_LOCKYZ                1035
#define IDC_CHECK_YAW_DETENTS           1036
#define IDC_EDIT_YAW_DETENTS            1037
#define IDC_CHECK_PITCH_DETENTS         1038
#define IDC_EDIT_PITCH_DETENTS          1039
#define IDC_CHECK_ROLL_DETENTS          1040
#define IDC_EDIT_ROLL_DETENTS           1041
#define IDC_CHECK_SNAPX                 1042
#define IDC_EDIT_SNAPX                  1043
#define IDC_COMBO1                      1044
#define IDC_COMBO_PLACEMENTMODE         1044
#define IDC_CHECK_SNAPY                 1045
#define IDC_EDIT_SNAPY                  1046
#define IDC_CHECK_SNAPZ                 1048
#define IDC_EDIT_SNAPZ                  1049
#define ID_EDIT_TRIGGERRENDERDOCCAPTURE 32771
#define ID_EDIT_DELETE                  32772
#define ID_EDIT_DUPLICATE               32773
#define ID_VIEW_GRAPHEDITOR             32776
#define ID_GRAPH_ADDNODE                32777
#define ID_GRAPH_DELETENODE             32778
#define ID_EDIT_CUT32779                32779
#define ID_EDIT_COPY32780               32780
#define ID_EDIT_PASTE32781              32781
#define ID_EDIT_EXECUTESELECTION        32782
#define ID_EDIT_EXECUTE                 32783
#define ID_EDIT_CLEAR32784              32784
#define ID_EDIT_SAVE                    32785
#define ID_EDIT_LOAD                    32786
#define ID_CUT                          32787
#define ID_CLEAR                        32788
#define ID_EDIT_GROUP                   32794
#define ID_EDIT_UNGROUP                 32795
#define ID_EDIT_CENTERCAMERAON          32796
#define ID_Menu                         32797
#define ID_EDIT_CAMERASETTINGS          32798
#define ID_EDIT_RESOURCEPATHCONFIGURATION 32799
#define ID_RELOAD                       32800
#define ID_RELOAD_RELOAD                32801
#define ID_RESOURCE_OPENCONTAININGFOLDER 32802
#define ID_RESOURCE_OPEN                32803
#define ID_RESOURCESPY_OPEN             32804
#define ID_RESOURCESPY_OPENFOLDER       32805
#define ID_RESOURCE_OPENFOLDER          32806
#define ID_RESOURCE_RELOAD              32807
#define ID_RESOURCE_PROPERTIES          32808
#define ID_VIEW_HOVERINFORMATION        32809
#define ID_APP_ADVANCETIME              32810
#define ID_APP_EDITORDRAW               32811
#define ID_BUTTON32813                  32813
#define ID_VIEW_CAMERASETTINGS          32814
#define ID__OBJECTLIST                  32815
#define ID__PROPERTIES                  32816
#define ID__DEBUGOUTPUT                 32817
#define ID__RESOURCESPY                 32818
#define ID__SCRIPTEDITOR                32819
#define ID__PROTOTYPELIST               32820
#define ID_TOOLBARSANDDOCKINGWINDOWS_DEBUG 32821
#define ID_TOOLBARSANDDOCKINGWINDOWS_PROPERTIES 32822
#define ID_TOOLBARSANDDOCKINGWINDOWS_OBJECTS 32823
#define ID_TOOLBARSANDDOCKINGWINDOWS_PROTOTYPES 32824
#define ID_TOOLBARSANDDOCKINGWINDOWS_SCRIPTEDITOR 32825
#define ID_TOOLBARSANDDOCKINGWINDOWS_RESOURCESPY 32826
#define ID_DOCK_DEBUG                   32827
#define ID_DOCK_PROPERTIES              32828
#define ID_DOCK_OBJECTS                 32829
#define ID_DOCK_PROTOTYPES              32830
#define ID_DOCK_SCRIPT                  32831
#define ID_DOCK_SCRIPTS                 32832
#define ID_DOCK_RESOURCES               32833
#define ID_PROPS_DELETE                 32835
#define ID_HELP_SDKDOCUMENTATION        32836
#define ID_HELP_SDKDOCS                 32837
#define ID_HELP_COMPONENTGENERATOR      32838
#define ID_HELP_GENCOMPONENT            32839
#define ID_EDIT_ASSIGN                  32840
#define ID_EDIT_ASSIGNROOT              32841
#define ID_EDIT_PACKFILEREGISTRATION    32842
#define ID_EDIT_PACKFILEMANAGEMENT      32843
#define ID_APP_INTERACTABLE             32845
#define ID_EDIT_BRUSHSETTINGS           32847

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        354
#define _APS_NEXT_COMMAND_VALUE         32848
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           367
#endif
#endif
